/* Generated by the protocol buffer compiler.  DO NOT EDIT! */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "messages.pb-c.h"
void   uis_input_data__init
                     (UisInputData         *message)
{
  static UisInputData init_value = UIS_INPUT_DATA__INIT;
  *message = init_value;
}
size_t uis_input_data__get_packed_size
                     (const UisInputData *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_input_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uis_input_data__pack
                     (const UisInputData *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_input_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uis_input_data__pack_to_buffer
                     (const UisInputData *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_input_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UisInputData *
       uis_input_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UisInputData *)
     protobuf_c_message_unpack (&uis_input_data__descriptor,
                                allocator, len, data);
}
void   uis_input_data__free_unpacked
                     (UisInputData *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_input_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   uis_pkt__init
                     (UisPkt         *message)
{
  static UisPkt init_value = UIS_PKT__INIT;
  *message = init_value;
}
size_t uis_pkt__get_packed_size
                     (const UisPkt *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_pkt__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t uis_pkt__pack
                     (const UisPkt *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_pkt__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t uis_pkt__pack_to_buffer
                     (const UisPkt *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_pkt__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
UisPkt *
       uis_pkt__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (UisPkt *)
     protobuf_c_message_unpack (&uis_pkt__descriptor,
                                allocator, len, data);
}
void   uis_pkt__free_unpacked
                     (UisPkt *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &uis_pkt__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t uis_input_data__count__default_value = 1;
static const ProtobufCFieldDescriptor uis_input_data__field_descriptors[3] =
{
  {
    "type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisInputData, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisInputData, count),
    NULL,
    &uis_input_data__count__default_value,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisInputData, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uis_input_data__field_indices_by_name[] = {
  2,   /* field[2] = body */
  1,   /* field[1] = count */
  0,   /* field[0] = type */
};
static const ProtobufCIntRange uis_input_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor uis_input_data__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "UisInputData",
  "UisInputData",
  "UisInputData",
  "",
  sizeof(UisInputData),
  3,
  uis_input_data__field_descriptors,
  uis_input_data__field_indices_by_name,
  1,  uis_input_data__number_ranges,
  (ProtobufCMessageInit) uis_input_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
const ProtobufCEnumValue uis_pkt__pkt_cmd__enum_values_by_number[6] =
{
  { "INPUT", "UIS_PKT__PKT_CMD__INPUT", 1 },
  { "INIT", "UIS_PKT__PKT_CMD__INIT", 268435457 },
  { "OPEN", "UIS_PKT__PKT_CMD__OPEN", 268435458 },
  { "CLOSE", "UIS_PKT__PKT_CMD__CLOSE", 268435459 },
  { "CLOSE_SOURCE", "UIS_PKT__PKT_CMD__CLOSE_SOURCE", 268435460 },
  { "IOCTL", "UIS_PKT__PKT_CMD__IOCTL", 268435461 },
};
static const ProtobufCIntRange uis_pkt__pkt_cmd__value_ranges[] = {
{1, 0},{268435457, 1},{0, 6}
};
const ProtobufCEnumValueIndex uis_pkt__pkt_cmd__enum_values_by_name[6] =
{
  { "CLOSE", 3 },
  { "CLOSE_SOURCE", 4 },
  { "INIT", 1 },
  { "INPUT", 0 },
  { "IOCTL", 5 },
  { "OPEN", 2 },
};
const ProtobufCEnumDescriptor uis_pkt__pkt_cmd__descriptor =
{
  PROTOBUF_C_ENUM_DESCRIPTOR_MAGIC,
  "UisPkt.PktCmd",
  "PktCmd",
  "UisPkt__PktCmd",
  "",
  6,
  uis_pkt__pkt_cmd__enum_values_by_number,
  6,
  uis_pkt__pkt_cmd__enum_values_by_name,
  2,
  uis_pkt__pkt_cmd__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor uis_pkt__field_descriptors[7] =
{
  {
    "sourceId",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, sourceid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "moduleId",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, moduleid),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "seq",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, seq),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cmd",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, cmd),
    &uis_pkt__pkt_cmd__descriptor,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, type),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, count),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "body",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(UisPkt, body),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned uis_pkt__field_indices_by_name[] = {
  6,   /* field[6] = body */
  3,   /* field[3] = cmd */
  5,   /* field[5] = count */
  1,   /* field[1] = moduleId */
  2,   /* field[2] = seq */
  0,   /* field[0] = sourceId */
  4,   /* field[4] = type */
};
static const ProtobufCIntRange uis_pkt__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor uis_pkt__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "UisPkt",
  "UisPkt",
  "UisPkt",
  "",
  sizeof(UisPkt),
  7,
  uis_pkt__field_descriptors,
  uis_pkt__field_indices_by_name,
  1,  uis_pkt__number_ranges,
  (ProtobufCMessageInit) uis_pkt__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor uis_service__method_descriptors[2] =
{
  { "Open", &uis_pkt__descriptor, &uis_pkt__descriptor },
  { "Ioctl", &uis_pkt__descriptor, &uis_pkt__descriptor },
};
const unsigned uis_service__method_indices_by_name[] = {
  1,        /* Ioctl */
  0         /* Open */
};
const ProtobufCServiceDescriptor uis_service__descriptor =
{
  PROTOBUF_C_SERVICE_DESCRIPTOR_MAGIC,
  "UisService",
  "Open",
  "UisService",
  "",
  2,
  uis_service__method_descriptors,
  uis_service__method_indices_by_name
};
void uis_service__open(ProtobufCService *service,
                       const UisPkt *input,
                       UisPkt_Closure closure,
                       void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &uis_service__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void uis_service__ioctl(ProtobufCService *service,
                        const UisPkt *input,
                        UisPkt_Closure closure,
                        void *closure_data)
{
  PROTOBUF_C_ASSERT (service->descriptor == &uis_service__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void uis_service__init (UisService_Service *service,
                        UisService_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &uis_service__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
